---

- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: copy hosts
  copy: src=hosts.{{ stage }} dest=/etc/hosts owner=root group=root mode=0644 backup=yes

- name: yum update
  yum: state=latest name=*

- name: install needed packages
  yum:
    name: '{{ item }}'
    state: installed
  with_items:
    - sysstat
    - net-tools
    - telnet
    - iotop
    - tmux
