---

- name: install rdo repo
  yum:
    name: https://rdoproject.org/repos/rdo-release.rpm
    state: present

- name: install sshpass
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - sshpass

- name: copy password.{{ stage }}
  copy: src=password.{{ stage }}  dest=/root/password.txt owner=root group=root mode=0644 backup=yes

- name: Generate SSH keys
  shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
  args:
    creates: /root/.ssh/id_rsa

- name: Copy SSH keys to {{ controller_ip }}
  command: sshpass -f /root/password.txt ssh-copy-id -o StrictHostKeyChecking=no {{ controller_ip }}

- name: Copy SSH keys to {{ compute1_ip }}
  command: sshpass -f /root/password.txt ssh-copy-id -o StrictHostKeyChecking=no {{ compute1_ip }}

- name: Copy SSH keys to {{ compute2_ip }}
  command: sshpass -f /root/password.txt ssh-copy-id -o StrictHostKeyChecking=no {{ compute2_ip }}

- name: Copy SSH keys to {{ storage1_ip }}
  command: sshpass -f /root/password.txt ssh-copy-id -o StrictHostKeyChecking=no {{ storage1_ip }}

